# Spring properties
spring:
  application:
     name: account-microservice


# Server configuration
server:
  context-path: /micro
  port: 8080


# Cloudant Configuration
cloudant:
    db: accountdb
    username: a09a53a7-097a-4b55-899d-18dc714aabba-bluemix
    password: 3de0d46817cdaf50ded0b3a98eeeef48b062d44071bba7a193aa4b31bfb722f8
    url: https://a09a53a7-097a-4b55-899d-18dc714aabba-bluemix:3de0d46817cdaf50ded0b3a98eeeef48b062d44071bba7a193aa4b31bfb722f8@a09a53a7-097a-4b55-899d-18dc714aabba-bluemix.cloudant.com
